/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonGroup: typeof import('./src/components/ButtonGroup/ButtonGroup.vue')['default']
    CricleButton: typeof import('./src/components/CricleButton.vue')['default']
    ModalWithBackButton: typeof import('./src/components/Modal/ModalWithBackButton.vue')['default']
    QRCodeModal: typeof import('./src/components/Modal/QRCodeModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
